---
- name: Creates directory for scanner firmware
  ansible.builtin.file:
    path: /var/app/
    state: directory
    
- name: Copy file to remote system
  copy:
    src: ./../build/scanner
    dest: /var/app/scanner
    mode: '0755'