---
- name: Creates directory for scanner firmware
  ansible.builtin.file:
    path: /var/app/
    state: directory
    
- name: Copy file to remote system
  copy:
    src: ./../build/scanner
    dest: /var/app/scanner
    mode: '0755'

- name: Register service with systemd
  copy:
    src: scanner.service
    dest: /etc/systemd/system/
    mode: '0755'

- name: Reload systemd scanner Service
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    enabled: true
    name: scanner